plugins:
  - serverless-dynamodb-local
  - serverless-offline
service: life-app-api
frameworkVersion: '2'
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  apiGateway:
    shouldStartNameWithService: true
  environment:
    NODE_ENV: 14.17
  iamRoleStatements: ${file(iam/lifeAppTableIAM.yml)}
resources:
  Resources:
    lifeAppTable: ${file(resources/lifeAppTable.yml):lifeAppTable}
functions:
  app:
    handler: dist/serverless.handler
    events:
      - http:
          method: any
          path: /{any+}
custom:
  lifeAppTable:
    name: lifeApp
    arn: !GetAtt lifeAppTable.Arn
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      migrate: true
      port: 8000
